name: Sync iOS AppIcon (reusable)

on:
  workflow_call:
    inputs:
      zip:
        type: string
        required: false
        default: "AppIcons.zip"
      target:
        type: string
        required: false
        default: "ios/Runner/Assets.xcassets/AppIcon.appiconset"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract AppIcons.zip and locate AppIcon.appiconset
        id: locate
        run: |
          set -euo pipefail
          ZIP="${{ inputs.zip }}"
          echo "ZIP=$ZIP" >> "$GITHUB_ENV"

          [ -f "$ZIP" ] || { echo "✗ $ZIP not found"; exit 1; }

          mkdir -p _appicon_zip
          unzip -q "$ZIP" -d _appicon_zip

          if [ -d "_appicon_zip/Assets.xcassets/AppIcon.appiconset" ]; then
            SRC="_appicon_zip/Assets.xcassets/AppIcon.appiconset"
          elif [ -d "_appicon_zip/AppIcon.appiconset" ]; then
            SRC="_appicon_zip/AppIcon.appiconset"
          else
            echo "✗ Could not find AppIcon.appiconset in the zip."
            exit 1
          fi

          [ -f "$SRC/Contents.json" ] || { echo "✗ Missing Contents.json"; exit 1; }
          echo "SRC=$SRC" >> "$GITHUB_OUTPUT"

      - name: Copy AppIcon into iOS asset catalog
        run: |
          TARGET="${{ inputs.target }}"
          mkdir -p "$TARGET"
          rm -rf "$TARGET"/*
          cp -R "${{ steps.locate.outputs.SRC }}"/. "$TARGET"/
          echo "✓ Copied AppIcon to $TARGET"

      - name: Commit if changed
        run: |
          TARGET="${{ inputs.target }}"
          if [ ! -d "$TARGET" ]; then
            echo "No target dir; nothing to commit."
            exit 0
          fi
          if git diff --quiet --exit-code -- "$TARGET"; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add "$TARGET"
            git commit -m "chore(ios): sync AppIcon from ${ZIP:-AppIcons.zip}"
            git push
          fi
